name: Update GitHub Variables
description: Updates or creates GitHub variables based on a YAML
author: lexops

inputs:
  token:
    description: GitHub Access Token
    required: false

runs:
  using: node20
  main: dist/index.js
