repos:
  - name: lexops/update-gh-vars
    environments:
      - environment_name: staging
        deployment_branch_policy:
          protected_branches:
            - main
          custom_branch_policies:
            - ref: 'feature/*'
        variables:
          - name: STAGING_FOO
            value: foo_value
          - name: STAGING_BAR
            value: bar_value
    variables:
      - name: FOO
        value: bar
      - name: BAR
        value: baz
