name: Example Workflow

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  update-variables:
    name: Update GitHub Variables
    runs-on: ubuntu-latest

    steps:
      - name: Update GitHub Variables
        id: update-gh-vars
        uses: lexops/update-gh-vars@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          yaml-config: |
            repos:
              - name: lexops/update-gh-vars
                variables:
                  - name: FOO
                    value: bar
                  - name: BAR
                    value: baz
